### PR TITLE
Add game manual and modify Usage.rst

### PR DESCRIPTION
**Pull request by uvidyadharan**
Demo site can be found [here](https://ftcdocs-testing-uvid.readthedocs.io/en/latest/)

### CODE REVIEW

**Comment by cmacfarl** [comment]
Just curious, in what capacity is docker being used here?

**Comment by uvidyadharan** [comment]
For me it makes it really easy to just test across computers because all I need to do is a `docker compose up` and its running on a local port. Its a neat thing that I would entirely get not adding to the main repo but it does in my experience make development really easy though most people would prefer just doing a `make html` which probably makes sense. Its something I have though so I might as well offer it. It also makes it work well with docker dev environments which I also like using.

**Comment by texasdiaz** [comment]
The whole point of the /stubs directory was to make it painfully obvious to anyone who is paying attention that the documentation stubs are actually stubs, and that nobody intends for that content to be "real". This also gives us a way to determine how many "fake" pages we have, as all "fake" pages should be stubs. I'm not okay with just moving the stubs out.

**Comment by texasdiaz** [comment]
I wanted to add a bit of context here as well, if you're considering "fixing" the organization: I'd like to mimic the structure of the WPILib documentation. I want all pages organized within topics and be within their own directory, For instance, CAD should have a structure such as:

/docs/source/cad
- index.rst
- /ptc-onshape
- /ptc-onshape/ptc-onshape.rst
- /ptc-onshape/images
- /autodesk-fusion
- /autodesk-fusion/autodesk-fusion.rst
- /autodesk-fusion/images
- /dassault-systems-solidworks
- /dassault-systems-solidworks/dassault-systems-solidworks.rst
- /dassault-systems-solidworks/images

The index.rst explains what CAD is used for, why it's good, and so on, and contains links to each of the individual CAD system files. Then the individual .rst files in the directories help explain specifics for each CAD system, how to get and use for free, links to tutorials for that system, and so on. The /images directory would then store all the images that the .rst file needed.

I hope this makes sense. I do not want the main /docs/source directory to just be littered with .rst files with no organization and some master /images file for all the images we need. I want organization and cleanup to be simple, even if developing the organization takes a little elbow grease.

**Review by texasdiaz — APPROVED** [review]

**Pull request merged**
